### ISSUE TITLE
Баг "вакансия не доступна"

### ISSUE THREAD

**Issue by orestx** [msp4/shopper#62]
Если сначала активную вакансию деактивировать, а потом снова активировать, то в списке вакансий она отображается, но если перейти на нее - получаю сообщение "вакансия не доступна".

![image](https://cloud.githubusercontent.com/assets/2162824/9303814/4d80a850-44ea-11e5-92cc-4f9942d3bf5b.png)

Так же, "недоступна" пишется раздельно.

**Comment by orestx** [comment]
Хотя, кажется она такой стала не от того что я перед этим ее деактивировал, в общем нужно еще разобраться в чем причина. Но проблема есть.

**Comment by orestx** [comment]
![image](https://cloud.githubusercontent.com/assets/2162824/9304773/65752670-44f4-11e5-818f-93e783a6dec3.png)

**Comment by orestx** [comment]
Возможно если решить эту проблему: https://github.com/msp4/shopper/issues/63
решится и наша...

**Comment by orestx** [comment]
Новые данные. Это как то связанно с локацией. Смотря какую локацию указываю - то работает, то нет.
При чем такое проявляется и в новой учетной записи и в старой.
Что бы воспреизвести, мне достаточно в адресе локации указать:  город Стрый, Львовская область, Украина
Указывал Львов, как то через раз, то норм то нет. В общем не понятки. Но изменение локации влияло на поведение бага, то есть то нет.. Еще завтра попробую докопаться то конкретной причины

**Comment by orestx** [comment]
Теперь у меня разные города дают одинаковый эффект.
Что еще заметил.. 
Создал вакансию (с локацией, естественно, иначе не создастся):
![image](https://cloud.githubusercontent.com/assets/2162824/9382605/25672c28-474b-11e5-95ff-995feaecb97e.png)

Смотрю локации текущего исследования и вижу, что ничего не вижу:
![image](https://cloud.githubusercontent.com/assets/2162824/9382619/33ca0876-474b-11e5-8db7-ac81fdfd3d2b.png)

Хотя ТП эту вакансию в списке видит, просто не может посмотреть (вакансия не доступна)

**Comment by orestx** [comment]
Но пока что не понятно, почему в некоторых случаях не добавляет

**Comment by orestx** [comment]
Почему не добавлялась локация не понятно, но причина бага "вакансия не доступна" кроется в фильтрах по локации. Дело в том что, если я укажу в локации исследования город "Первый", а будучи ТП на странице поиска вакансий, укажу город "Второй", который находится, например за 70 км от города "Первый" и перетяну ползунок расстаяния в положение 100км, то я этот город увижу в списке доступных вакансий. Но, при попытке просмотреть доп. информацию, то есть при клике на город, увижу сообщение "вакансия не доступна". Зато, если в адресе для поиска вакансий указать конкретно город "Первый", то вакансия будет мне отображаться. Получается на стороне client.msp4.me выполняется проверка ТП, и там косяк с расстоянием, поэтому ТП проверку на стороне клиента не проходит и не получает доступа к информации о вакансии.

**Comment by vladmokryi** [comment]
стояло условие которое подставляло 25км в радиус если координаты берутся из req.body
пока исправил на 150км, нужно еще разбираться

**Comment by orestx** [comment]
ок
