### ISSUE TITLE
Вакансия публикуется сразу, в обход корзины

### ISSUE THREAD

**Issue by orestx** [msp4/shopper#63]
Я смог опубликовать вакансии, не оплачивая их. Нажал опубликовать и не попадая в корзину они стали доступными для ТП.

**Comment by vladmokryi** [comment]
@orestx насколько я понимаю вакансии добавляются сразу когда их добавляет клиент, оплачивает он уже заявку которую шоппер пришлет ( потому как шопер может предложить свою цену ). У меня  все нормально добавляет, такого как на скринах "вакансия не доступна" (+ошибка доступа в конслоь) нету. А когда деактивирую, оно пропадает у шопера, но только если  перед этим перегружу страницу.

**Comment by orestx** [comment]
точно, все норм.
