### ISSUE TITLE
Валидація на почту при реєстрації

### ISSUE THREAD

**Issue by Iryna-Ivasko** [msp4/shopper#65]
В нас немає ніякої валідації на почту, зробити хоча б мінімальне валдікування на наявність xxxxxx@xxx

**Comment by vladmokryi** [comment]
вхід на shopper тільки через соціальні акаунти

**Comment by Iryna-Ivasko** [comment]
Так, випадково переплутала з клієнтом(зараз і там все норм). Закриваю
