### ISSUE TITLE
Рекомендовані вакансії

### ISSUE THREAD

**Issue by Iryna-Ivasko** [msp4/shopper#67]
Може, в рекомендованих вакансіях показувати не тільки ті, що шукав ТП (не тільки по тому місту), а і ті що є в містах, що в казані в його профілі в "местонахождение"? http://www.screencast.com/users/Iryna.Ivasko/folders/MSP4/media/cbf63faa-a304-4cf4-ade9-c5d04c8d061f

**Comment by vladmokryi** [comment]
66 таска на клієнті

**Comment by Iryna-Ivasko** [comment]
видаляю
